name: ubuntu_test_installed_version.yml


on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: install library
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release --log-level=DEBUG -DCMAKE_INSTALL_PREFIX=./install_dir
          cmake --build ./build -j$(nproc)
          cmake --install ./build --prefix ./install_dir
          rm -rf build

      - name: configure with installed version via cmake
        run: CMAKE_PREFIX_PATH="./install_dir" cmake -S. -Bbuild2 -DMAGIC_ENUM_OPT_TEST_INSTALLED_VERSION=1 --log-level=DEBUG

      - name: build with installed version via cmake
        run: cmake --build build2 --config Debug -j$(nproc) --verbose

      - name: test
        run: |
          cd build2
          ctest --build-config Debug -j$(nproc)

      - name: clear 
        run: rm -rf build2

      - name: configure with installed version via pkgconfig
        run: CMAKE_PREFIX_PATH="./install_dir" cmake -S. -Bbuild3 -DMAGIC_ENUM_OPT_TEST_INSTALLED_VERSION_PKGCONFIG=1 -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=1 --log-level=DEBUG

      - name: build with installed version via pkgconfig
        run: cmake --build build3 --config Debug -j$(nproc) --verbose

      - name: test
        run: |
          cd build3
          ctest --build-config Debug -j$(nproc)
